import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { addOrderPayment, fetchDashboardTodos, fetchOrder, fetchOrders, updateOrderStatus } from '../utils/api'
import type { DashboardTodos, Order, OrderStatus, PaymentMethod } from '../utils/api'

const statusLabels: Record<OrderStatus, string> = { pending_purchase: '待采购', preparing: '备货中', pending_delivery: '待交付', delivered: '已交付', cancelled: '已取消' }
const paymentLabels: Record<PaymentMethod, string> = { cash: '现金', wechat: '微信', alipay: '支付宝', transfer: '转账', other: '其他' }
function money(cents: number) { return new Intl.NumberFormat('zh-CN', { style: 'currency', currency: 'CNY' }).format((Number(cents) || 0) / 100) }
function date(value: string) { return value ? new Date(value).toLocaleString('zh-CN', { hour12: false }) : '—' }
function snLink(order: Order, item: NonNullable<Order['items']>[number]) { const params = new URLSearchParams({ orderItemId: String(item.id), orderNo: order.orderNo, productName: item.name, quantity: String(item.quantity), bound: String(item.boundSnCount) }); if (item.productId) params.set('productId', String(item.productId)); return `/sn?${params.toString()}` }

export function OrdersPage() { const [orders, setOrders] = useState<Order[]>([]); const [error, setError] = useState(''); useEffect(() => { fetchOrders().then(setOrders).catch((err: unknown) => setError(err instanceof Error ? err.message : '订单加载失败')) }, []); return <section className="orders-page"><div className="orders-page-head"><div><p className="orders-kicker">订单管理</p><h2>订单列表</h2></div><Link className="btn primary" to="/quotes">新建报价</Link></div>{error ? <p className="orders-error">{error}</p> : <div className="orders-table-wrap"><table className="orders-table"><thead><tr><th>订单号</th><th>客户</th><th>合计</th><th>已收</th><th>状态</th><th>更新时间</th></tr></thead><tbody>{orders.length === 0 ? <tr><td colSpan={6} className="orders-empty">暂无订单，可从报价工作台转为订单。</td></tr> : orders.map((order) => <tr key={order.id}><td><Link to={`/orders/${order.id}`}>{order.orderNo}</Link></td><td>{order.customerName}</td><td>{money(order.totalCents)}</td><td>{money(order.paidCents)}</td><td><span className={`order-status status-${order.status}`}>{statusLabels[order.status]}</span></td><td>{date(order.updatedAt)}</td></tr>)}</tbody></table></div>}</section> }

export function OrderDetailPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [order, setOrder] = useState<Order | null>(null); const [error, setError] = useState(''); const [payAmount, setPayAmount] = useState(''); const [method, setMethod] = useState<PaymentMethod>('transfer'); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false); const orderId = Number(id); const remaining = useMemo(() => Math.max(0, (order?.totalCents ?? 0) - (order?.paidCents ?? 0)), [order]); const reload = () => fetchOrder(orderId).then(setOrder).catch((err: unknown) => setError(err instanceof Error ? err.message : '订单加载失败'))
  useEffect(() => { if (Number.isInteger(orderId) && orderId > 0) reload(); else setError('订单编号无效') }, [orderId])
  const savePayment = async () => { const amountCents = Math.round(Number(payAmount) * 100); if (!amountCents || amountCents < 0) { setError('请输入大于零的收款金额'); return }; setSaving(true); setError(''); try { await addOrderPayment(orderId, { amountCents, paymentMethod: method, remark: note.trim() }); setPayAmount(''); setNote(''); reload() } catch (err) { setError(err instanceof Error ? err.message : '登记收款失败') } finally { setSaving(false) } }
  const setStatus = async (status: OrderStatus) => { setSaving(true); setError(''); try { await updateOrderStatus(orderId, status); reload() } catch (err) { setError(err instanceof Error ? err.message : '更新状态失败') } finally { setSaving(false) } }
  if (error && !order) return <section className="orders-page"><p className="orders-error">{error}</p><button className="btn" onClick={() => navigate('/orders')}>返回订单列表</button></section>
  if (!order) return <section className="orders-page">正在加载订单...</section>
  return <section className="orders-page"><div className="orders-page-head"><div><p className="orders-kicker">订单详情</p><h2>{order.orderNo}</h2><span>{order.customerName}{order.projectTitle ? ` · ${order.projectTitle}` : ''}</span></div><div><Link className="btn" to="/orders">返回列表</Link><Link className="btn" to="/sn" style={{ marginLeft: 8 }}>SN 管理</Link></div></div>{error && <p className="orders-error">{error}</p>}<div className="order-summary-grid"><div><span>订单合计</span><strong>{money(order.totalCents)}</strong></div><div><span>已收金额</span><strong>{money(order.paidCents)}</strong></div><div><span>待收金额</span><strong>{money(remaining)}</strong></div><div><span>当前状态</span><strong><span className={`order-status status-${order.status}`}>{statusLabels[order.status]}</span></strong></div></div><div className="order-detail-grid"><section className="order-card"><h3>配置明细</h3><table className="orders-table"><thead><tr><th>分类</th><th>配置</th><th>数量</th><th>单价</th><th>小计</th><th>SN 绑定</th></tr></thead><tbody>{(order.items ?? []).map((item) => { const pending = Math.max(0, item.quantity - item.boundSnCount); const bindable = Boolean(item.productId); return <tr key={item.id}><td>{item.category}</td><td>{item.name}<small>{item.details}</small></td><td>{item.quantity}</td><td>{money(item.unitPriceCents)}</td><td>{money(item.lineTotalCents ?? item.quantity * item.unitPriceCents)}</td><td><div className="order-sn-state"><strong>已绑 {item.boundSnCount} / {item.quantity}</strong><small>待绑 {pending}</small>{bindable ? <Link to={snLink(order, item)}>{pending ? '绑定 SN' : '查看 SN'}</Link> : <small>未关联可序列化商品</small>}</div></td></tr> })}</tbody></table></section><aside className="order-card order-actions"><h3>履约状态</h3><select disabled={saving} value={order.status} onChange={(event) => void setStatus(event.target.value as OrderStatus)}>{(Object.keys(statusLabels) as OrderStatus[]).map((status) => <option value={status} key={status}>{statusLabels[status]}</option>)}</select><h3>登记收款</h3><label>金额（元）<input inputMode="decimal" placeholder={remaining ? (remaining / 100).toFixed(2) : '0.00'} value={payAmount} onChange={(event) => setPayAmount(event.target.value)} /></label><label>方式<select value={method} onChange={(event) => setMethod(event.target.value as PaymentMethod)}>{(Object.keys(paymentLabels) as PaymentMethod[]).map((paymentMethod) => <option key={paymentMethod} value={paymentMethod}>{paymentLabels[paymentMethod]}</option>)}</select></label><label>备注<input value={note} onChange={(event) => setNote(event.target.value)} /></label><button className="btn primary" disabled={saving || !remaining} onClick={() => void savePayment()}>登记收款</button></aside></div></section>
}

export function DashboardPage() { const [todos, setTodos] = useState<DashboardTodos | null>(null); const [error, setError] = useState(''); useEffect(() => { fetchDashboardTodos().then(setTodos).catch((err: unknown) => setError(err instanceof Error ? err.message : '待办加载失败')) }, []); const cards = [{ label: '今日订单', value: todos?.todayOrders, unit: '笔' }, { label: '待采购', value: todos?.pendingPurchase, unit: '笔' }, { label: '待交付', value: todos?.pendingDelivery, unit: '笔' }, { label: '待收款', value: todos ? money(todos.receivableCents) : '—', unit: '' }]; return <section className="orders-page"><div className="orders-page-head"><div><p className="orders-kicker">经营概览</p><h2>今日待办</h2></div></div>{error ? <p className="orders-error">{error}</p> : <div className="todo-grid">{cards.map((card) => <article className="todo-card" key={card.label}><span>{card.label}</span><strong>{card.value ?? '—'}</strong><small>{card.unit}</small></article>)}</div>}</section> }
