import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { bindSNs, fetchProducts, fetchSNDetail, fetchSNList, manualEntrySN, precheckSNRegistration, registerSNs, warrantyCheck } from '../utils/api'
import type { Product, SerialNumber, SNBatchPrecheck, SNEvent, SNManualEntryInput, SNRegisterInput, SNWarrantyCheckItem } from '../utils/api'

const statusLabels: Record<string, string> = { in_stock: '在库', reserved: '已锁定', picked: '已领料', delivered: '已交付', in_service: '售后中', returned_to_supplier: '已退供应商', scrapped: '已报废' }
const warrantyLabels: Record<string, { label: string; className: string }> = { in_warranty: { label: '在保', className: 'badge-green' }, expiring_soon: { label: '临期', className: 'badge-yellow' }, expired: { label: '过保', className: 'badge-red' }, not_sold: { label: '未售', className: 'badge-gray' } }
const eventLabels: Record<string, string> = { inbound: '入库', reserved: '锁定', unreserved: '解锁', picked: '领料', delivered: '交付', returned: '退货', replaced: '换件', returned_to_supplier: '退供应商', scrapped: '报废', manual_entry: '人工补录' }
const MAX_BATCH_SIZE = 500
function money(cents: number) { return new Intl.NumberFormat('zh-CN', { style: 'currency', currency: 'CNY' }).format((cents || 0) / 100) }
function dateStr(value: string | null) { return value || '—' }
function todayStr() { return new Date().toISOString().split('T')[0] }
function parseCodes(value: string) { return value.split(/[\n,]+/).map((code) => code.trim().toUpperCase().replace(/\s+/g, '')).filter(Boolean) }
function localPrecheck(codes: string[]): SNBatchPrecheck { const unique = new Set<string>(); const inputDuplicates: string[] = []; codes.forEach((code) => unique.has(code) ? inputDuplicates.push(code) : unique.add(code)); const accepted = [...unique].slice(0, MAX_BATCH_SIZE); return { total: codes.length, validCodes: accepted, inputDuplicates, existingCodes: [], overLimitCodes: [...unique].slice(MAX_BATCH_SIZE) } }

export function SerialNumberPage() {
  const [searchParams] = useSearchParams()
  const contextOrderItemId = Number(searchParams.get('orderItemId')) || 0
  const contextProductId = Number(searchParams.get('productId')) || 0
  const contextProductName = searchParams.get('productName') || ''
  const contextOrderNo = searchParams.get('orderNo') || ''
  const contextQuantity = Math.max(0, Number(searchParams.get('quantity')) || 0)
  const contextBound = Math.max(0, Number(searchParams.get('bound')) || 0)
  const contextPending = Math.max(0, contextQuantity - contextBound)
  const [items, setItems] = useState<SerialNumber[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [q, setQ] = useState(''); const [status, setStatus] = useState(''); const [warranty, setWarranty] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const [checkQ, setCheckQ] = useState(''); const [checkResults, setCheckResults] = useState<SNWarrantyCheckItem[] | null>(null); const [detail, setDetail] = useState<SerialNumber | null>(null)
  const [showRegister, setShowRegister] = useState(false); const [regProductId, setRegProductId] = useState(''); const [regText, setRegText] = useState(''); const [regRef, setRegRef] = useState(''); const [regCost, setRegCost] = useState(''); const [regMonths, setRegMonths] = useState('36'); const [regResult, setRegResult] = useState<{ inserted: number; duplicates: string[] } | null>(null); const [regPrecheck, setRegPrecheck] = useState<SNBatchPrecheck | null>(null); const [checkingRegister, setCheckingRegister] = useState(false)
  const [showManual, setShowManual] = useState(false); const [manProductId, setManProductId] = useState(''); const [manSN, setManSN] = useState(''); const [manName, setManName] = useState(''); const [manPhone, setManPhone] = useState(''); const [manDelivered, setManDelivered] = useState(todayStr()); const [manMonths, setManMonths] = useState('36'); const [manRemark, setManRemark] = useState('')
  const [showBind, setShowBind] = useState(false); const [bindSNText, setBindSNText] = useState(''); const [selectedSNIds, setSelectedSNIds] = useState<number[]>([]); const [availableSNs, setAvailableSNs] = useState<SerialNumber[]>([]); const [binding, setBinding] = useState(false)
  const [products, setProducts] = useState<Product[]>([])
  const registerCodes = useMemo(() => parseCodes(regText), [regText])
  const fallbackPrecheck = useMemo(() => localPrecheck(registerCodes), [registerCodes])
  const effectivePrecheck = regPrecheck ?? fallbackPrecheck

  const load = async () => { setLoading(true); setError(''); try { const data = await fetchSNList({ q, status: status || undefined, warranty: warranty || undefined, productId: contextProductId || undefined, page, pageSize: 20 }); setItems(data.items); setTotal(data.total) } catch (e) { setError(e instanceof Error ? e.message : '加载SN列表失败') } finally { setLoading(false) } }
  // 筛选变化时异步刷新台账，避免 effect 内同步 setState。
  useEffect(() => { const timer = window.setTimeout(() => { void (async () => { setLoading(true); setError(''); try { const data = await fetchSNList({ q, status: status || undefined, warranty: warranty || undefined, productId: contextProductId || undefined, page, pageSize: 20 }); setItems(data.items); setTotal(data.total) } catch (e) { setError(e instanceof Error ? e.message : '加载SN列表失败') } finally { setLoading(false) } })() }, 0); return () => window.clearTimeout(timer) }, [page, q, status, warranty, contextProductId])
  useEffect(() => { const timer = window.setTimeout(() => { fetchProducts({ pageSize: 200 }).then((data) => setProducts(data.items.filter((product) => product.is_serialized))).catch(() => {}) }, 0); return () => window.clearTimeout(timer) }, [])
  const doSearch = () => { setPage(1); void load() }
  const doWarrantyCheck = async () => { if (!checkQ.trim()) return; setCheckResults(null); try { const result = await warrantyCheck(checkQ.trim()); setCheckResults(result.items) } catch (e) { setError(e instanceof Error ? e.message : '查询失败') } }
  const openDetail = async (id: number) => { try { setDetail(await fetchSNDetail(id)) } catch { setError('加载SN详情失败') } }
  const checkRegister = async () => { if (!regProductId || !registerCodes.length) return; setCheckingRegister(true); setError(''); try { setRegPrecheck(await precheckSNRegistration({ productId: Number(regProductId), snCodes: registerCodes })) } catch (e) { setError(e instanceof Error ? e.message : '录入预检失败') } finally { setCheckingRegister(false) } }
  const doRegister = async () => { if (!regProductId || !registerCodes.length) { setError('请选择商品并输入SN码'); return }; if (!regPrecheck) { await checkRegister(); return }; if (!regPrecheck.validCodes.length) { setError('没有可录入的有效SN码'); return }; try { const input: SNRegisterInput = { productId: Number(regProductId), snCodes: regPrecheck.validCodes, purchaseRef: regRef, purchaseCostCents: Math.round(Number(regCost) * 100), warrantyMonths: Number(regMonths) || 36 }; const result = await registerSNs(input); setRegResult({ inserted: result.inserted, duplicates: result.duplicates }); setNotice(`成功录入 ${result.inserted} 条${result.duplicates.length ? `，${result.duplicates.length} 条重复已跳过` : ''}`); void load() } catch (e) { setError(e instanceof Error ? e.message : '录入失败') } }
  const doManual = async () => { if (!manProductId || !manSN.trim() || !manName.trim() || !manPhone.trim() || !manDelivered) { setError('请填写所有必填字段'); return }; try { const input: SNManualEntryInput = { productId: Number(manProductId), snCode: manSN.trim(), customerName: manName.trim(), customerPhone: manPhone.trim(), deliveredAt: manDelivered, warrantyMonths: Number(manMonths) || 36, remark: manRemark }; const result = await manualEntrySN(input); setShowManual(false); setNotice(`补录成功，保修到期 ${result.warrantyExpiresOn}`); void load() } catch (e) { setError(e instanceof Error ? e.message : '补录失败') } }
  const toggleSN = (id: number) => setSelectedSNIds((selected) => selected.includes(id) ? selected.filter((value) => value !== id) : [...selected, id])
  const doBind = async () => { if (!contextOrderItemId) { setError('请从订单明细的“绑定 SN”进入，系统会自动识别对应订单行'); return }; const typedCodes = parseCodes(bindSNText); const typedIds = typedCodes.map((code) => availableSNs.find((sn) => sn.sn_code === code)?.id).filter((id): id is number => id !== undefined); const missing = typedCodes.filter((code) => !availableSNs.some((sn) => sn.sn_code === code)); const ids = [...new Set([...selectedSNIds, ...typedIds])]; if (missing.length) { setError(`未找到可绑定的SN码：${missing.join('、')}`); return }; if (!ids.length) { setError('请勾选或输入至少一个SN码'); return }; if (contextPending && ids.length > contextPending) { setError(`该订单行还需绑定 ${contextPending} 条SN，当前选择了 ${ids.length} 条`); return }; setBinding(true); try { const result = await bindSNs({ orderItemId: contextOrderItemId, snIds: ids }); setShowBind(false); setNotice(`已成功绑定 ${result.bound} 条SN`); void load() } catch (e) { setError(e instanceof Error ? e.message : 'SN绑定失败') } finally { setBinding(false) } }
  async function openBind() { setBindSNText(''); setSelectedSNIds([]); setShowBind(true); if (!contextOrderItemId || !contextProductId) { setAvailableSNs([]); return }; try { const data = await fetchSNList({ status: 'in_stock', productId: contextProductId, pageSize: 100 }); setAvailableSNs(data.items) } catch { setAvailableSNs([]); setError('可绑定SN加载失败') } }

  return <section className="sn-page"><div className="sn-page-head"><div><h2>SN 台账</h2><p>{contextOrderItemId ? `正在为订单 ${contextOrderNo || '—'} 的 ${contextProductName || '指定商品'} 绑定SN` : '配件 SN 码记录与客户过保查询'}</p></div><div className="sn-actions"><button className="btn primary" onClick={() => { setRegResult(null); setRegPrecheck(null); setRegText(''); setRegRef(''); setRegCost(''); setRegMonths('36'); setShowRegister(true) }}>录入SN</button><button className="btn" onClick={() => { setManSN(''); setManName(''); setManPhone(''); setManRemark(''); setManMonths('36'); setManDelivered(todayStr()); setShowManual(true) }}>补录老客户</button>{!contextOrderItemId && <button className="btn" onClick={() => { setError('请从订单明细的“绑定 SN”进入，系统会自动识别订单行和商品') }}>绑定订单</button>}</div></div>
    {contextOrderItemId && <div className="sn-context"><strong>订单行待绑定：{contextPending} 条</strong><span>已绑 {contextBound} / {contextQuantity} 条</span><button className="btn primary" disabled={contextPending === 0} onClick={() => void openBind()}>{contextPending ? '选择SN并绑定' : '已全部绑定'}</button></div>}
    {error && <div className="sn-alert error">{error}<button onClick={() => setError('')}>关闭</button></div>}{notice && <div className="sn-alert success">{notice}<button onClick={() => setNotice('')}>关闭</button></div>}
    <div className="sn-check-bar"><input placeholder="输入 SN 码或客户手机号查保修" value={checkQ} onChange={(event) => setCheckQ(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && void doWarrantyCheck()} /><button className="btn primary" onClick={() => void doWarrantyCheck()}>查保修</button></div>
    {checkResults && <div className="sn-check-results">{checkResults.length === 0 ? <p className="sn-empty">未找到匹配的 SN 记录</p> : checkResults.map((result, index) => <div key={index} className="sn-check-card"><span className={`sn-badge ${warrantyLabels[result.warrantyStatus]?.className || 'badge-gray'}`}>{warrantyLabels[result.warrantyStatus]?.label || result.warrantyStatus}</span><strong>{result.snCode}</strong><span className="sn-meta">{result.customerName} {result.customerPhone} · 交付 {dateStr(result.deliveredAt)} · 保修至 {dateStr(result.warrantyExpiresOn)}</span></div>)}</div>}
    <div className="sn-filters"><input placeholder="搜索 SN / 客户 / 手机号" value={q} onChange={(event) => setQ(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && doSearch()} /><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }}><option value="">全部状态</option>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><select value={warranty} onChange={(event) => { setWarranty(event.target.value); setPage(1) }}><option value="">保修状态</option><option value="in_warranty">在保</option><option value="expiring_soon">30天内临期</option><option value="expired">已过保</option><option value="not_sold">未售</option></select><button className="btn" onClick={doSearch}>查询</button></div>
    <div className="sn-table-wrap"><table className="sn-table"><thead><tr><th>SN 码</th><th>商品</th><th>客户</th><th>交付日</th><th>保修到期</th><th>状态</th></tr></thead><tbody>{loading ? <tr><td colSpan={6}>正在加载...</td></tr> : items.length === 0 ? <tr><td colSpan={6} className="sn-empty">暂无 SN 记录</td></tr> : items.map((sn) => <tr key={sn.id} onClick={() => void openDetail(sn.id)} className="sn-row-clickable"><td><strong>{sn.sn_code}</strong></td><td>{sn.product_name || `#${sn.product_id}`}</td><td>{sn.current_customer_name || '—'}</td><td>{dateStr(sn.delivered_at)}</td><td>{sn.warranty_expires_on || '—'}</td><td><span className="sn-badge">{statusLabels[sn.status] || sn.status}</span></td></tr>)}</tbody></table></div>
    {total > 20 && <div className="sn-pages"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>上一页</button><span>{page} / {Math.ceil(total / 20)}（共 {total} 条）</span><button disabled={page * 20 >= total} onClick={() => setPage(page + 1)}>下一页</button></div>}
    {showRegister && <div className="sn-overlay" onClick={() => setShowRegister(false)}><div className="sn-modal" onClick={(event) => event.stopPropagation()}><h3>SN 批量入库</h3><label>商品<select value={regProductId} onChange={(event) => { setRegProductId(event.target.value); setRegPrecheck(null) }}><option value="">请选择</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>SN 码（一行一个，或用逗号分隔）<textarea rows={8} placeholder="SN001&#10;SN002&#10;SN003" value={regText} onChange={(event) => { setRegText(event.target.value); setRegPrecheck(null) }} /></label><div className="sn-precheck"><strong>提交前检查</strong><span>有效 {effectivePrecheck.validCodes.length} 条</span><span>输入重复 {effectivePrecheck.inputDuplicates.length} 条</span><span>数据库已存在 {effectivePrecheck.existingCodes.length} 条</span><span>超出上限 {effectivePrecheck.overLimitCodes.length} 条（单次最多 {MAX_BATCH_SIZE} 条）</span>{(effectivePrecheck.inputDuplicates.length > 0 || effectivePrecheck.existingCodes.length > 0 || effectivePrecheck.overLimitCodes.length > 0) && <small>将跳过：{[...effectivePrecheck.inputDuplicates, ...effectivePrecheck.existingCodes, ...effectivePrecheck.overLimitCodes].join('、')}</small>}</div><label>采购单号（可选）<input value={regRef} onChange={(event) => setRegRef(event.target.value)} /></label><label>进货单价（元，可选）<input type="number" step="0.01" value={regCost} onChange={(event) => setRegCost(event.target.value)} /></label><label>质保月数<input type="number" value={regMonths} onChange={(event) => setRegMonths(event.target.value)} /></label>{regResult && <p>本次结果：已录入 {regResult.inserted} 条{regResult.duplicates.length ? `，数据库重复跳过 ${regResult.duplicates.length} 条：${regResult.duplicates.join('、')}` : ''}</p>}<div className="sn-modal-actions"><button className="btn" onClick={() => setShowRegister(false)}>关闭</button><button className="btn" disabled={!regProductId || !registerCodes.length || checkingRegister} onClick={() => void checkRegister()}>{checkingRegister ? '检查中...' : '检查可录入SN'}</button><button className="btn primary" disabled={!regPrecheck?.validCodes.length} onClick={() => void doRegister()}>确认录入</button></div></div></div>}
    {showManual && <div className="sn-overlay" onClick={() => setShowManual(false)}><div className="sn-modal" onClick={(event) => event.stopPropagation()}><h3>补录老客户 SN</h3><label>商品<select value={manProductId} onChange={(event) => setManProductId(event.target.value)}><option value="">请选择</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label>SN 码<input value={manSN} onChange={(event) => setManSN(event.target.value.toUpperCase())} /></label><label>客户姓名<input value={manName} onChange={(event) => setManName(event.target.value)} /></label><label>客户电话<input value={manPhone} onChange={(event) => setManPhone(event.target.value)} /></label><label>交付日期<input type="date" value={manDelivered} onChange={(event) => setManDelivered(event.target.value)} /></label><label>质保月数<input type="number" value={manMonths} onChange={(event) => setManMonths(event.target.value)} /></label><label>备注<input value={manRemark} onChange={(event) => setManRemark(event.target.value)} /></label><div className="sn-modal-actions"><button className="btn" onClick={() => setShowManual(false)}>取消</button><button className="btn primary" onClick={() => void doManual()}>确认补录</button></div></div></div>}
    {showBind && <div className="sn-overlay" onClick={() => setShowBind(false)}><div className="sn-modal sn-bind-modal" onClick={(event) => event.stopPropagation()}><h3>为订单行绑定 SN</h3><p className="sn-bind-help">{contextOrderNo || '当前订单'} · {contextProductName || '指定商品'} · 还需 {contextPending} 条。仅展示该商品可绑定的在库 SN。</p><label>连续输入 SN 编码（回车、逗号或换行分隔）<textarea rows={3} value={bindSNText} onChange={(event) => setBindSNText(event.target.value.toUpperCase())} placeholder="SN001&#10;SN002" /></label><div className="sn-available"><p>勾选可绑定 SN（已选 {selectedSNIds.length} 条）：</p>{availableSNs.length ? <ul>{availableSNs.map((sn) => <li key={sn.id}><label><input type="checkbox" checked={selectedSNIds.includes(sn.id)} onChange={() => toggleSN(sn.id)} /> <strong>{sn.sn_code}</strong> <span>{sn.product_name || '商品'}</span></label></li>)}</ul> : <p className="sn-empty">暂无该商品可绑定的在库SN</p>}</div><div className="sn-modal-actions"><button className="btn" onClick={() => setShowBind(false)}>取消</button><button className="btn primary" disabled={binding || contextPending === 0} onClick={() => void doBind()}>{binding ? '绑定中...' : '确认绑定'}</button></div></div></div>}
    {detail && <div className="sn-overlay" onClick={() => setDetail(null)}><div className="sn-detail" onClick={(event) => event.stopPropagation()}><h3>SN 详情</h3><dl className="sn-detail-grid"><div><dt>SN 码</dt><dd>{detail.sn_code}</dd></div><div><dt>商品</dt><dd>{detail.product_name || `#${detail.product_id}`}</dd></div><div><dt>状态</dt><dd>{statusLabels[detail.status] || detail.status}</dd></div><div><dt>采购单号</dt><dd>{detail.purchase_ref || '—'}</dd></div><div><dt>进价</dt><dd>{detail.purchase_cost_cents ? money(detail.purchase_cost_cents) : '—'}</dd></div><div><dt>入库日期</dt><dd>{dateStr(detail.inbound_at)}</dd></div><div><dt>客户</dt><dd>{detail.current_customer_name || '—'} {detail.current_customer_phone}</dd></div><div><dt>交付日期</dt><dd>{dateStr(detail.delivered_at)}</dd></div><div><dt>质保月数</dt><dd>{detail.warranty_months}</dd></div><div><dt>保修到期</dt><dd>{dateStr(detail.warranty_expires_on)}</dd></div><div><dt>备注</dt><dd>{detail.remark || '—'}</dd></div></dl>{detail.events?.length ? <><h4>流转记录</h4><div className="sn-timeline">{detail.events.map((event: SNEvent, index) => <div key={index} className="sn-timeline-item"><span className="sn-timeline-dot" /><div><strong>{eventLabels[event.event_type] || event.event_type}</strong><small>{event.occurred_at?.replace('T', ' ').slice(0, 16)}</small></div>{(event.customer_name || event.remark) && <p>{[event.customer_name, event.remark].filter(Boolean).join(' · ')}</p>}</div>)}</div></> : null}<button className="btn" onClick={() => setDetail(null)}>关闭</button></div></div>}
  </section>
}
